name: Build Open Pose Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3

    - name: Clone additional repositories
      run: |
        cd 18.0
        mkdir src
        mkdir src/OCA
        git clone https://github.com/oca/server-ux.git src/OCA
        git clone https://github.com/oca/connector.git src/OCA
        ls src/OCA

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Publish Docker Image
      run: |
        timetag=(`date +%Y%M%d`)
        cd 18.0
        docker build . --tag ghcr.io/odoonix/open-pose:18.0.${timetag} --tag ghcr.io/odoonix/open-pose:18.0
        docker push ghcr.io/odoonix/open-pose:18.0
        docker push ghcr.io/odoonix/open-pose:18.0.${timetag}
